---
title: "Cheetah Map"
description: |
    A Contribution to the BES Movement "MoveMap" Competition 2021.
author:
    - name: Cédric Scherer
url: https://www.cedricscherer.com  
affiliation: Self-Employed | IZW Berlin
- name: Jörg Melzheimer
url: https://www.cheetah-research.org/joerg-melzheimer
affiliation: IZW Berlin
affiliation_url: http://www.izw-berlin.de/en/
    date: "`r Sys.Date()`"
output: 
    distill::distill_article:
    highlight: kate       ## choose code style
code_folding: hide    ## hide or show code by default?
code_download: true 
editor_options: 
    chunk_output_type: console
---
    
    ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = TRUE, retina = 1)
Sys.setlocale("LC_TIME", "C")
```

```{r packages}
library(tidyverse)
library(sf)
library(stars)
library(raster)
library(elevatr)
library(purrr)
library(ggspatial)
library(ggnewscale)
library(cowplot)
library(colorspace)
library(systemfonts)
library(here)
library(glue)
library(pdftools)
```


## Data

```{r prep-data}
proj <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
```


### Communication Hubs

```{r data-hubs}
## 0 Communication hub borders
path <- here("data", "0 Communication hub borders")

## KDEs P Hub
sf_kde50 <- st_read(dsn = glue("{path}/KDE50/P068kde50_tgf.shp")) %>% 
  st_transform(crs = proj)
sf_kde95 <- st_read(dsn = glue("{path}/KDE95/P068kde95_tgf.shp")) %>% 
  st_transform(crs = proj)

## KDEs Neighbouring Hubs
sf_kde_neighb <- 
  st_read(dsn = glue("{path}/Neigbouring hubs/HS_merged190128.shp")) %>% 
  st_transform(crs = proj) %>% 
  filter(level == 50) %>%  
  mutate(id = 1:28) %>% 
  filter(id %in% c(2, 15, 22))


## Calculate KDEs new
# terri <- read_csv(glue("{path}/Terri raw data/P068_tgf.csv")) %>% 
#   dplyr::select(`location.long`, `location.lat`) %>% 
#   SpatialPoints()
# 
# proj4string(terri) = CRS(proj)
# ud <- kernelUD(terri, extent = .1)
# 
# vers <- function(r) {
#   getverticeshr(ud, r, unout = "km2") %>% 
#     st_as_sf() 
# }
# 
# kdes <- map_df(rev(seq(50, 95, by = 5)), vers)
```

### Marking Trees

```{r data-trees}
## 1 marking trees
sf_trees <- st_read(dsn = here("data", "1 marking trees", "mt_201022.shp")) %>% 
  st_transform(crs = proj) 
```

### Floaters

```{r data-floaters}
## 2 floaters
ids <- 
  list.files(path = here("data", "2 floaters"), full.names = FALSE) %>% 
  as_tibble() %>% 
  mutate(
    ## remove file format
    id = str_remove(value, ".csv"), 
    filename = as.character(1:n())
  ) %>% 
  dplyr::select(-value)

df_floaters <- 
  list.files(path = here("data", "2 floaters"), full.names = TRUE) %>%
  map_dfr(read_csv, .id = "filename") %>% 
  janitor::clean_names() %>% 
  left_join(ids) %>% 
  dplyr::select(id, event_id:location_lat, 
                tag_local_identifier, individual_local_identifier) %>% 
  group_by(id) %>% 
  mutate(step = 1:n())

sf_floaters <- 
  df_floaters %>% 
  filter(
    !is.na(location_long), !is.na(location_lat),
    id %in% c("P151-5552", "P152-7077", "P153-7417"), #"P150-6409", "P155-3534"
  ) %>% 
  mutate(
    year = lubridate::year(timestamp), 
    month = lubridate::month(timestamp),
    yday = lubridate::yday(timestamp)
  ) %>% 
  ungroup() %>% 
  st_as_sf(coords = c("location_long", "location_lat"), crs = proj)
```

### Elevation Data

```{r hillshade-overview}
bbox_overview <- as(extent(17.1, 18.3, -22.5, -21), 'SpatialPolygons')
crs(bbox_overview) <- crs(proj)

file_ov <- here("data", "3 raster data", "dem_overview.tif")

if(!file.exists(file_ov)) {
  dem_ov <- get_elev_raster(locations = bbox_overview, z = 11, proj = proj)
  dem_ov@data@values <- dem_ov@data@values * 10
  writeRaster(dem_ov, file_ov)
} else {
  dem_ov <- raster(file_ov)
}

slope_ov <- terrain(dem_ov, opt = "slope", unit = "radians")
aspect_ov <- terrain(dem_ov, opt = "aspect", unit = "radians")

sf_hill_ov <-
  hillShade(slope_ov, aspect_ov, 40, 270) %>%
  aggregate(fact = 3, method = "bilinear") %>% 
  focal(w = matrix(1/9, nc = 3, nr = 3), mean) %>% 
  rasterToPoints() %>%
  as_tibble() %>% 
  st_as_stars()

sf_slope_ov <-
  slope_ov %>%
  aggregate(fact = 3, method = "bilinear") %>%
  rasterToPoints() %>%
  as_tibble() %>%
  ## invert the scale so that more slope is darker
  mutate(slope = 1 - slope) %>% 
  st_as_stars()
```

```{r hillshade-hub}
bbox_hub <- as(extent(17.7, 17.78, -21.84, -21.79), 'SpatialPolygons')
crs(bbox_hub) <- crs(proj)

file_hub <- here("data", "3 raster data", "dem_hub.tif")

if(!file.exists(file_hub)) {
  dem_hub <- get_elev_raster(locations = bbox_hub, z = 14, proj = proj)
  dem_hub@data@values <- dem_hub@data@values * 10
  writeRaster(dem_hub, file_hub)
} else {
  dem_hub <- raster(file_hub)
}

slope_hub <- terrain(dem_hub, opt = "slope", unit = "radians")
aspect_hub <- terrain(dem_hub, opt = "aspect", unit = "radians")

sf_hill_hub <-
  hillShade(slope_hub, aspect_hub, 40, 270) %>%
  aggregate(fact = 5, method = "bilinear") %>% 
  focal(w = matrix(1/9, nc = 3, nr = 3), mean) %>% 
  rasterToPoints() %>%
  as_tibble() %>% 
  st_as_stars()

sf_slope_hub <-
  slope_hub %>%
  aggregate(fact = 5, method = "bilinear") %>%
  rasterToPoints() %>%
  as_tibble() %>%
  ## invert the scale so that more slope is darker
  mutate(slope = 1 - slope) %>% 
  st_as_stars()
```

### Tree Cover

```{r tree-cover}
sf_tc <- 
  raster(here("data", "3 raster data", "Hansen_GFC2015_treecover2000_20S_010E.tif")) %>% 
  crop(bbox_overview) %>% 
  aggregate(fact = 10) %>%
  #aggregate(fact = 100) %>% 
  st_as_stars() %>% 
  mutate(Hansen_GFC2015_treecover2000_20S_010E = if_else(
    Hansen_GFC2015_treecover2000_20S_010E < .1, NA_real_, Hansen_GFC2015_treecover2000_20S_010E
  ))
```


## Maps P Hub

```{r plotting-prep}
## ggplot theme
theme_set(theme_light(base_size = 18, base_family = "Lora")) #Amplitude-Regular

theme_update(
  panel.grid = element_blank(),
  panel.border = element_rect(size = 2, color = "grey12", fill = NA),
  axis.title = element_blank(),
  axis.ticks = element_line(color = "grey12"),
  axis.ticks.length = unit(.7, "lines"),
  axis.text = element_text(color = "grey12"),
  legend.key = element_rect(fill = NA, color = NA),
  legend.key.width = unit(3, "lines"),
  legend.key.height = unit(1.3, "lines"),
  legend.text = element_text(size = 17),
  legend.background = element_rect(fill = NA, color = NA),
  plot.margin = margin(rep(25, 4))
)

## color palette
pal <- c("#0f936c", "#8b1996", "#3969AC")
# based on rcartocolor::carto_pal(n = 4, name = "Bold")[c(2, 1, 3)] 
```


```{r map-data-prep}
## map projection (UTM S33)
map_proj <- "+proj=utm +zone=33 +south +ellps=bess_nam +towgs84=616,97,-251,0,0,0,0 +units=m +no_defs"

## labeling of individuals
sf_ind <- 
  tibble(id = c("P151-5552", "P152-7077", "P153-7417")) %>% 
  mutate(geom = st_sfc(
    st_point(c(17.812, -21.958)), 
    st_point(c(17.6725, -21.988)), 
    st_point(c(17.99, -21.753))
  )) %>% 
  st_as_sf(crs = proj)

## labeling of hubs
sf_hub <- 
  #tibble(hub = c("P Hub", "Neighbouring Hubs")) %>% 
  tibble(hub = c("P Hub")) %>% 
  mutate(geom = st_sfc(
    st_point(c(17.842, -21.854))#, 
    #st_point(c(17.957, -21.806))
  )) %>% 
  st_as_sf(crs = proj)

## labeling of legend items
sf_leg <- 
  tibble(lab = c(
    "Territory Holders", 
    "Floating Individuals",
    "Core areas as 50% KDE of four cheetahs (red)\nHome range as 95% KDE of one cheetah (grey)",
    "GPS tracks of three cheetahs\n1 June 2020 – 7 January 2021"
  )) %>% 
  mutate(geom = st_sfc(
    st_point(c(17.37, -21.726)),
    st_point(c(17.37, -21.777)),
    st_point(c(17.37, -21.737)),
    st_point(c(17.37, -21.788))
  )) %>% 
  st_as_sf(crs = proj)

## textboxes
sf_textbox <- 
  tibble(lab = c(
    "Solving the Cheetah-Farmer Conflict in Namibia","Rural central Namibia is one of the most important strongholds of the declining global\ncheetah population. Here, the rarest large African cat lives on privately owned farm-\nland. A traditional conflict poses a threat to them as they occasionally prey on cattle\ncalves. New insights into the cheetah’s spatial behaviour provide a viable solution\nto this human-wildlife conflict: “communication hubs” form hotspots of\ncheetah activity, leading to substantially less activity in the vast areas\nbetween the cores of the territories.",
    "Scientists from the Cheetah Research Project, led by the\nLeibniz Institute for Zoo and Wildlife Research (IZW),\ndiscovered two interesting details of the cheetah's spatial\nbehaviour by collecting long-term movmenent data:\n\n(1) Cheetah males display two spatial tactics: floating\nindividuals roam over vast areas whereas territory holders\ndefend small core areas (Melzheimer et al. 2018 Ecosphere).\n\n(2) These core areas of male cheetah territories serve as\n“communication hubs” (Melzheimer et al. 2020 PNAS).\n\nImplementing this knowledge and moving their breeding\nherds with young calves out of the hotspots, farmers were\nable to reduce livestock losses by more than 80 percent.\n\nThe map illustrates the movement behaviour of three\nfloaters that regularly visit these communication hubs.\nAll of them frequently move into the “P Hub” during the\nperiod from 16 to 31 December 2020 (highlighted tracks).",
    "Graphic: Cédric Scherer\nIcons: Stephanie Gendera\nData: Melzheimer et al. 2020 PNAS\n\nwww.cheetah-research.org"
  )) %>% 
  mutate(geom = st_sfc(
    st_point(c(17.298, -21.587)),
    st_point(c(17.298, -21.609)),
    st_point(c(17.925, -21.868)),
    st_point(c(17.298, -22.162))
  )) %>% 
  st_as_sf(crs = proj)

##  labels for scale bar
sf_scale <-
  tibble(lab = c("0", "10", "20", "30 km")) %>% 
  mutate(geom = st_sfc(
    st_point(c(17.875, -22.187)),
    st_point(c(17.971, -22.187)),
    st_point(c(18.067, -22.187)),
    st_point(c(18.163, -22.187))
  )) %>% 
  st_as_sf(crs = proj)
  
## background and main data (+ turn into trajectories)
sf_all_line <-
  sf_floaters %>% 
  filter(
    #(year == 2020 & month %in% 9:12) | (year == 2021)
    (year == 2020 & month %in% 6:12) | (year == 2021)
  ) %>%
  group_by(id)  %>%
  summarise(do_union = FALSE) %>%
  st_cast("LINESTRING")

sf_highlight <-
  sf_floaters %>% 
  filter(yday %in% 348:366 & year == 2020)

sf_highlight_line <-
  sf_floaters %>% 
  filter(yday %in% 348:366 & year == 2020)  %>% 
  group_by(id)  %>%
  summarise(do_union = FALSE) %>%
  st_cast("LINESTRING") 
```

### Overview Map

```{r map-overview}
overview <- 
  sf_all_line %>% 
  ggplot() + 
    
    ## Hillshading -------------------------------------------------------------
    geom_stars(data = sf_hill_ov) +
    geom_stars(data = sf_slope_ov, alpha = .8) +
    #scale_fill_gradient(high = "#edc6b6", low = "#461f11") + # for rcarto
    scale_fill_gradient(high = "#f5e9d7", low = "#654619") + #BROWN for gradient
    new_scale_fill() +
    
    ## KDE Fills ---------------------------------------------------------------
    geom_sf(data = sf_kde95, fill = "grey30", color = NA, alpha = .18) + 
    geom_sf(data = sf_kde50, fill = "#871a1a", color = NA, alpha = .66) + 
    
    ## KDEs Neighbouring Hubs Fill ---------------------------------------------
    geom_sf(data = sf_kde_neighb, fill = "#871a1a", color = NA, alpha = .4) +
  
    ## Tree Cover --------------------------------------------------------------
    #geom_stars(data = sf_tc, alpha = .25) +
    #rcartocolor::scale_fill_carto_c(palette = "Emrld") +
    geom_stars(data = sf_tc, alpha = .33) +
    scale_fill_gradient(low = "#347136", high = "#1b3b1c") + 
    
    ## Trajectories Outline ----------------------------------------------------
    geom_sf(color = "#edd8b8", size = 1.4) + 
    geom_sf(data = sf_highlight_line, color = "#edd8b8", size = 2.3) + 
  
    ## Trajectories Background -------------------------------------------------
    geom_sf(
      aes(color = id, color = after_scale(desaturate(lighten(color, .33), .55))),
      size = .8
    ) +
  
    ## KDE95 Shadow ------------------------------------------------------------
    geom_sf(
      data = sf_kde95 %>% st_buffer(dist = .0014), 
      fill = NA, color = "#35353566", size = 1.7
    ) + 
    
    ## KDE95 Outline -----------------------------------------------------------
    geom_sf(data = sf_kde95, fill = NA, color = "grey25", size = .55) + #, linetype = "11"
  
    ## Trajectories Highlight --------------------------------------------------
    geom_sf(data = sf_highlight_line, aes(color = id), size = .8) + 
  
    ## KDE50 Outline -----------------------------------------------------------
    geom_sf(data = sf_kde50, color = "#871a1a", fill = NA, size = .9) +#linetype = "11", size = .85) +
  
    ## KDEs Neighbouring Hubs --------------------------------------------------
    geom_sf(data = sf_kde_neighb, color = "#871a1a", fill = NA, linetype = "13", size = .65) +
  
    ## Legend ------------------------------------------------------------------
    geom_sf_text(
      data = sf_leg[1:2,], aes(label = lab),
      family = "Lora", size = 5, color = "black",
      fontface = "bold", hjust = 0
    ) +
    geom_sf_text(
        data = sf_leg[3:4,], aes(label = lab),
        family = "Lora", size = 3.6, color = "black",
        fontface = "italic", hjust = 0, vjust = 1, lineheight = 1
      ) +
    
    ## Labels ------------------------------------------------------------------
    geom_sf_text(
      data = sf_ind, aes(color = id, label = id),
      family = "Bebas Neue", size = 5.2
    ) +
    geom_sf_text(
      data = sf_hub[1,], aes(label = hub),
      family = "Bebas Neue", size = 6.2, color = "black", hjust = 0
    ) +
  
    ## Textboxes ---------------------------------------------------------------
    ## -> Title
    geom_sf_text(
      data = sf_textbox[1,], aes(label = lab),
      family = "Lora", size = 7, color = "black",
      fontface = "bold.italic", hjust = 0
    ) +
    ## -> Introduction
    geom_sf_text(
      data = sf_textbox[2,], aes(label = lab),
      family = "Lora", size = 3.6, color = "black",
      fontface = "italic", hjust = 0, vjust = 1, lineheight = 1.12
    ) +
    ## -> Background Information
    geom_sf_text(
      data = sf_textbox[3,], aes(label = lab),
      family = "Lora", size = 3.6, color = "black",
      fontface = "italic", hjust = "outward", vjust = 1
    ) +
    ## -> Cpation
    geom_sf_text(
      data = sf_textbox[4,], aes(label = lab),
      family = "Lora", size = 3.6, color = "black",
      fontface = "bold.italic", hjust = 0, lineheight = 1.1
    ) +
    
    ## Scalebar ----------------------------------------------------------------
    annotation_scale(
      location = "br", line_width = 1.3, width_hint = 0.4, text_col = NA, 
      height = unit(0.3, "cm"), pad_x = unit(0.6, "cm"), pad_y = unit(0.4, "cm")
    ) +
    ## -> Manual labels
    geom_sf_text(
      data = sf_scale, aes(label = lab),
      family = "Bebas Neue", size = 4.2, color = "black", fontface = "bold"
    ) +
    
    ## Scales + Coordinate System ----------------------------------------------
    coord_sf(expand = FALSE) + 
    scale_x_continuous(
      breaks = seq(17.3, 18.1, by = .1),
      labels = c(glue("{format(seq(17.3, 18.1, by = .1), nsmall = 1)}°E")), 
      limits = c(17.28, 18.18)
    ) +
    scale_y_continuous(
      labels = c(rev(glue("{format(seq(21.6, 22.2, by = .1), nsmall = 1)}°S"))), 
      limits = c(-22.21, -21.55)
    ) +
    scale_color_manual(values = pal) +
    theme(legend.position = "none")

## Final map with icons
overview_img <- 
  ggdraw(overview) +
    ## P Hub
    draw_image(here("img", "gepard-terri-main.png"), x = .614, y = .558, 
               hjust = .5, vjust = .5, width = .069) +
    ## Neighbouring hubs
    draw_image(here("img", "gepard-terri-other.png"), x = .512, y = .244, 
               hjust = .5, vjust = .5, width = .054) +
    draw_image(here("img", "gepard-terri-other.png"), x = .719, y = .859, 
               hjust = .5, vjust = .5, width = .054) +
    draw_image(here("img", "gepard-terri-other.png"), x = .89, y = .834, 
               hjust = .5, vjust = .5, width = .054) +
    ## floater
    draw_image(here("img", "gepard-floater1a.png"), x = .606, y = .435, 
               hjust = .5, vjust = .5, width = .049) +
    draw_image(here("img", "gepard-floater1b.png"), x = .468, y = .393, 
               hjust = .5, vjust = .5, width = .049) +
    draw_image(here("img", "gepard-floater1c.png"), x = .78, y = .72, 
               hjust = .5, vjust = .5, width = .049) +
    ## legend
    draw_image(here("img", "gepard-terri-main.png"), x = .142, y = .717,
              hjust = .5, vjust = .5, width = .072) +
    draw_image(here("img", "gepard-floater1.png"), x = .136, y = .644,
              hjust = .5, vjust = .5, width = .059) +
    ggsave(here::here("plots", glue("CheetahMap_gradient.pdf")), 
           width = 16, height = 12.2, device = cairo_pdf)
```


### Hub Map

```{r map-P-hub}
hub <- 
  sf_highlight_line %>% 
  ggplot() + 
    
  ## Hillshading -------------------------------------------------------------
    geom_stars(data = sf_hill_hub) +
    geom_stars(data = sf_slope_hub, alpha = .8) +
    scale_fill_gradient(high = "#f5e9d7", low = "#b47e2d", guide = "none") + #845c21
    new_scale_fill() +
    
    ## KDE95 Fill --------------------------------------------------------------
    geom_sf(data = sf_kde95, fill = "grey40", color = NA, alpha = .2) + ##ead2ae
  
    ## Tree Cover --------------------------------------------------------------
    geom_stars(data = sf_tc, alpha = .27) +
    #rcartocolor::scale_fill_carto_c(palette = "Emrld", guide = "none") +
    scale_fill_gradient(low = "#A5D6A7", high = "#1C5E1F", guide = "none") +  
  
    # Observations Outline ----------------------------------------------------
    geom_sf(data = sf_highlight, color = "#edd8b8", size = 4.5) +
  
    ## Trajectories Outline ----------------------------------------------------
    geom_sf(color = "#edd8b8", size = 2.7) +
  
    ## Trajectories ------------------------------------------------------------
    geom_sf(color = "white", size = 1.4) +
    geom_sf(aes(color = id), size = 1.4, alpha = .5) +
  
    ## Observations ------------------------------------------------------------
    geom_sf(data = sf_highlight, aes(color = id), 
            size = 2.2, shape = 21, fill = "#edd8b8", stroke = 1.4) +
  
    ## KDE95 Shadow ------------------------------------------------------------
    geom_sf(
      data = sf_kde50 %>% st_buffer(dist = .0005), 
      fill = NA, color = "#49494966", size = 1.4
    ) + #grey60
    
    ## KDE50 Outline -----------------------------------------------------------
    geom_sf(data = sf_kde50, color = "black", fill = NA, linetype = "22", size = .7) +
  
    ## Trees -------------------------------------------------------------------
    #geom_sf(data = sf_trees, shape = 5, color = "#006700", stroke = .4, size = 2) +
  
    ## Scales + Coordinate System ----------------------------------------------
    coord_sf(expand = FALSE, xlim = c(17.71, 17.76), ylim = c(-21.838, -21.792)) + #, crs = map_proj) +
    scale_x_continuous(limits = c(17.7, 17.77)) +
    scale_y_continuous(limits = c(-21.85, -21.78)) +
    scale_color_manual(values = pal) +
    ggsave(here::here("plots", "dev", glue("{format(Sys.time(), '%Y%m%d_%H%M%S')}_cheetah.pdf")), 
           width = 15, height = 15, device = cairo_pdf)
```


```{r convert-pdf}
pdfs <- list.files(here("plots"), pattern = "*.pdf")
for(pdf in pdfs) {
  pdf_convert(pdf = glue::glue("{here('plots')}/{pdf}"),
              filenames = glue::glue("{here('plots')}/{str_remove(pdf, '.pdf')}_hd.png"),
              format = "png", dpi = 800)
  
  pdf_convert(pdf = glue::glue("{here('plots')}/{pdf}"), 
              filenames = glue::glue("{here('plots')}/{str_remove(pdf, '.pdf')}_sd.png"),
              format = "png", dpi = 100)
}
```


<details><summary>Session Info</summary>
    
    ```{r sessionInfo, echo = F}
Sys.time()
git2r::repository()
sessionInfo()
```

</details>
    